[profile.default]
src = 'icm-contracts/avalanche/'
solc_version = '0.8.30'
evm_version = 'shanghai'
out = 'out'
libs = ['lib']
test = 'tests'
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200

[profile.common]
src = 'icm-contracts/common/'
solc_version = '0.8.30'
evm_version = 'shanghai'
viaIR = true

[profile.ethereum]
src = 'icm-contracts/ethereum/'
solc_version = '0.8.30'
evm_version = 'prague'

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = 'preserve'
multiline_func_header = 'params_first'
quote_style = 'double'
number_underscores = 'thousands'
override_spacing = true
wrap_comments = false

# Add the following to your VSCode settings to enable automatic formatting.
# {
#   "editor.formatOnSave": true,
#   "[solidity]": {
#     "editor.defaultFormatter": "JuanBlanco.solidity" 
#   },
#   "solidity.formatter": "forge",
# }
